services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: note_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
